name: "units-test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bartr/action-test@v1
      with:
        secrets: 'DOCKER_REPO DOCKER_USER DOCKER_PAT'
