name: "units-test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check secrets
      id: secrets
      uses: bartr/action-test@v1
      with:
        secrets: 'DOCKER_REPO DOCKER_USER DOCKER_PAT'

    - name: Check the output
      run: |
        # echo "isSet - ${{ steps.secrets.output.isSet }} "
        echo $IS_SET
        echo ${{ env.IS_SET }}
