name: "units-test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_SET: ${{ false }}

    steps:
    - uses: actions/checkout@v2

    - name: Check the output
      run: |
        if [[ "${{ secrets.DOCKER_PAT }}" != "" && "${{ secrets.DOCKER_REPO }}" != "" && "${{ secrets.DOCKER_USER}}" != "" ]];
        then
          echo "secret set"
          echo "::set-env name=DOCKER_SET::${{ true }}"
        fi

    - name: test DOCKER_SET
      run: |
        echo $DOCKER_SET

        if [ $DOCKER_SET == true ];
        then
          echo "Docker Set"
        fi
